"""rename

Revision ID: 46dae17ef788
Revises: d91bff8fbfb9
Create Date: 2025-12-07 19:17:05.303802

"""

from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '46dae17ef788'
down_revision: Union[str, Sequence[str], None] = 'd91bff8fbfb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'balance_adjustments',
        sa.Column('delta_dollars', sa.Numeric(), nullable=False),
        sa.Column('reason', sa.String(), nullable=False),
        sa.Column('tenant_id', sa.Integer(), nullable=False),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ['tenant_id'],
            ['tenants.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.drop_table('BalanceAdjustments')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'BalanceAdjustments',
        sa.Column('reason', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column('delta_dollars', sa.NUMERIC(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('BalanceAdjustments_tenant_id_fkey')),
        sa.PrimaryKeyConstraint('id', name=op.f('BalanceAdjustments_pkey')),
    )
    op.drop_table('balance_adjustments')
    # ### end Alembic commands ###
