"""rename

Revision ID: d91bff8fbfb9
Revises: 88fc4a1dd8d7
Create Date: 2025-12-07 16:28:15.746023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd91bff8fbfb9'
down_revision: Union[str, Sequence[str], None] = '88fc4a1dd8d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('BalanceAdjustments', sa.Column('delta_dollars', sa.Numeric(), nullable=False))
    op.drop_column('BalanceAdjustments', 'delta_cents')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('BalanceAdjustments', sa.Column('delta_cents', sa.NUMERIC(), autoincrement=False, nullable=False))
    op.drop_column('BalanceAdjustments', 'delta_dollars')
    # ### end Alembic commands ###
